version: "3"
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - ari
    environment:
      TARGETS: "5039"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  ari:
    image: wazopbx/asterisk
    ports:
      - "5039"
    volumes:
      - "./etc/asterisk:/etc/asterisk"
    command: "asterisk -fTvvv"
